#!/usr/bin/env python3
"""
extract_conversation.py

GRUG: Transcribe the CLI driver log into a clean user <-> grug conversation.

Pairs each `Brain > ` prompt line with the block of output that follows it,
then renders a Markdown log ready for attachment.

NO SILENT FAILURE: if stdin/stdout get out of sync (e.g. a /mission that
produced no AIML scaffold before the next Brain > prompt), the entry is still
emitted with a [no scaffold captured] marker so reviewers can see the gap
instead of quietly dropping a turn.
"""
import re
import sys
from pathlib import Path

LOG_PATH = Path("test_run/conversation_run.log")
INPUT_PATH = Path("test_run/conversation.txt")
OUT_PATH = Path("test_run/conversation_log.md")

# GRUG: The driver writes the CLI script line-by-line to stdin; the exact
# same ordering shows up in the log because the Brain loop reflects every
# command it accepted. We walk the input transcript and pair each line
# with the block of log output between successive `Brain >` markers.

def load_input_commands():
    """GRUG: user-side transcript --- one CLI command per line."""
    lines = []
    for raw in INPUT_PATH.read_text().splitlines():
        s = raw.strip()
        if not s:
            continue
        lines.append(s)
    return lines


def extract_scaffolds(log_text):
    """
    GRUG: Split the log into ordered (prompt_block) chunks.
    Every chunk starts at `Brain >` and ends at the next `Brain >` or EOF.
    We emit them as raw text blocks so the caller can pluck the AIML scaffold
    and telemetry without a second regex pass.
    """
    # Split keeping the delimiter attached to the block that follows it.
    parts = re.split(r"(?m)^Brain > ", log_text)
    # First part is pre-prompt boot text. Drop.
    return parts[1:]


def summarize_block(block):
    """
    GRUG: Pull the human-readable AIML scaffold plus the Primary Action /
    Winning Node / Confidence triple out of a log block.
    Falls back to the raw first line if no scaffold was emitted (e.g. /help,
    /status, /quit).
    """
    # AIML scaffold runs from the emoji header through the ============ footer.
    scaf = re.search(r"\ud83e\udd16 AIML Output Scaffold:\s*\n(.*?)\n=+", block, re.S)
    scaffold_text = scaf.group(1).strip() if scaf else None

    primary = re.search(r"Primary Action:\s*(\S+)\s+\(conf=([\d.]+),\s*certainty=(\S+)\)", block)
    winning = re.search(r"Winning Node:\s*(\S+)", block)
    lobe_ctx = re.search(r"Lobe Context:\s*(.+)", block)

    silent = "No valid specimens found for this input" in block

    return {
        "scaffold": scaffold_text,
        "primary": primary.groups() if primary else None,
        "winning": winning.group(1) if winning else None,
        "lobe_ctx": lobe_ctx.group(1).strip() if lobe_ctx else None,
        "silent": silent,
        "raw": block.strip(),
    }


def render_markdown(pairs, final_stats_block):
    lines = []
    lines.append("# Grug Live Conversation Log")
    lines.append("")
    lines.append("Generated by driving the unmodified GrugBot420 CLI via stdin redirection.")
    lines.append("Each entry shows the exact user command, Grug's primary action / winning")
    lines.append("node / confidence triple, and the full AIML output scaffold when emitted.")
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, (cmd, info) in enumerate(pairs, start=1):
        lines.append(f"## Turn {i}")
        lines.append("")
        lines.append(f"**User:** `{cmd}`")
        lines.append("")
        if info is None:
            lines.append("_(no log block captured --- likely a non-interactive command)_")
            lines.append("")
            continue
        if info["silent"] and not info["scaffold"]:
            lines.append("**Grug:** cave is silent on this one --- no specimens matched the input.")
            lines.append("")
            continue
        if info["primary"]:
            act, conf, cert = info["primary"]
            wn = info["winning"] or "n/a"
            lines.append(f"**Grug routing:** primary action = `{act}`  ·  confidence = `{conf}`  ·  certainty = `{cert}`  ·  winning node = `{wn}`")
            lines.append("")
        if info["scaffold"]:
            lines.append("**Grug output (AIML scaffold):**")
            lines.append("")
            lines.append("```")
            lines.append(info["scaffold"])
            lines.append("```")
            lines.append("")
        else:
            # GRUG: fall back to the raw block so nothing is ever silently lost.
            short = "\n".join(info["raw"].splitlines()[:12])
            lines.append("**Grug terminal output:**")
            lines.append("")
            lines.append("```")
            lines.append(short)
            lines.append("```")
            lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Final system stats")
    lines.append("")
    lines.append("```")
    lines.append(final_stats_block.strip())
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main():
    if not LOG_PATH.exists():
        print(f"!!! FATAL: log not found at {LOG_PATH} !!!", file=sys.stderr)
        sys.exit(1)
    if not INPUT_PATH.exists():
        print(f"!!! FATAL: input script not found at {INPUT_PATH} !!!", file=sys.stderr)
        sys.exit(1)

    log_text = LOG_PATH.read_text()
    commands = load_input_commands()
    blocks = extract_scaffolds(log_text)

    # GRUG: pair commands with blocks positionally. If counts do not line up we
    # still emit what we have and mark the tail None so the reader sees the
    # gap --- NO SILENT FAILURE.
    pairs = []
    for i, cmd in enumerate(commands):
        info = summarize_block(blocks[i]) if i < len(blocks) else None
        pairs.append((cmd, info))

    # GRUG: Final stats block --- we concatenate the last few pieces:
    # /status, /lobes, /nodes, /groupStatus, /crystalizeList, /attachments,
    # /listVerbs. We locate them by keyword in the raw log.
    stats_markers = [
        "GRUGBOT SYSTEM STATUS",
        "LOBE REGISTRY (",
        "NODE MAP STATUS (",
        "GROUP REGISTRY STATUS",
        "/crystalizeList:",
        "attachment map",
        "Verb classes",
    ]
    stats_chunks = []
    for marker in stats_markers:
        idx = log_text.rfind(marker)
        if idx == -1:
            continue
        end = log_text.find("\nBrain >", idx)
        if end == -1:
            end = len(log_text)
        stats_chunks.append(log_text[idx:end].strip())

    stats_text = "\n\n".join(stats_chunks) if stats_chunks else "(no stats markers found in log)"

    md = render_markdown(pairs, stats_text)
    OUT_PATH.write_text(md)
    print(f"wrote {OUT_PATH} ({len(md.splitlines())} lines)")


if __name__ == "__main__":
    main()
